import type { Order, VetProfile } from '../api'
import { publicAsset } from '../utils/publicAsset'

export const DEMO_USER = {
  id: 1,
  name: 'Иванов Алексей Петрович',
  phone: '+79990001122',
  email: 'demo@vet.ru',
  role: 'vet',
}

export const DEMO_TOKEN = 'demo-token'

export const DEMO_PROFILE: VetProfile = {
  id: 1,
  user_id: 1,
  specialization: 'Хирург, терапевт',
  experience_years: 8,
  rating: '4.90',
  reviews_count: 47,
  bio: 'Опытный ветеринарный врач с 8-летним стажем. Специализируюсь на хирургии и внутренних болезнях мелких домашних животных.',
  photo_url: publicAsset('ivanov-photo.jpg'),
  is_available: true,
  is_verified: true,
  lat: 55.7558,
  lng: 37.6173,
  created_at: new Date().toISOString(),
  name: 'Иванов Алексей Петрович',
  phone: '+79990001122',
  email: 'demo@vet.ru',
  // Career stats
  total_completed_orders: 62,   // Silver → нужно ещё 3 до Золота
  total_earnings: 214600,       // Gross сумма за все выполненные заказы
}

const now = new Date()
const addHours = (h: number) => new Date(now.getTime() + h * 3600000).toISOString()
const subHours = (h: number) => new Date(now.getTime() - h * 3600000).toISOString()

export const DEMO_ORDERS: Order[] = [
  {
    id: 1,
    client_id: 10,
    vet_id: null,
    pet_id: 5,
    service_id: 1,
    address: 'Москва, ул. Тверская, 15, кв. 42',
    address_lat: 55.7640,
    address_lng: 37.6033,
    scheduled_at: addHours(2),
    status: 'pending',
    notes: 'Кот не ест третий день, вялый',
    total_price: 2500,
    created_at: subHours(1),
    updated_at: subHours(1),
    client_name: 'Смирнова Анна Олеговна',
    client_phone: '+79161234567',
    pet_name: 'Барсик',
    pet_species: 'Кошка',
    pet_breed: 'Мейн-кун',
    service_name: 'Первичный осмотр',
    service_icon: '🩺',
    price_from: 2000,
    price_to: 3500,
    vet_name: null,
    history: [
      { id: 1, order_id: 1, status: 'pending', comment: 'Заказ создан, ищем ветеринара', created_at: subHours(1) },
    ],
  },
  {
    id: 2,
    client_id: 11,
    vet_id: 1,
    pet_id: 6,
    service_id: 3,
    address: 'Москва, Арбат, 28, кв. 7',
    address_lat: 55.7520,
    address_lng: 37.5924,
    scheduled_at: addHours(4),
    status: 'confirmed',
    notes: 'Собака хромает на заднюю лапу',
    total_price: 3200,
    created_at: subHours(3),
    updated_at: subHours(2),
    client_name: 'Петров Дмитрий Игоревич',
    client_phone: '+79267654321',
    pet_name: 'Рекс',
    pet_species: 'Собака',
    pet_breed: 'Лабрадор',
    service_name: 'Ортопедическая консультация',
    service_icon: '🦴',
    price_from: 3000,
    price_to: 5000,
    vet_name: 'Иванов Алексей Петрович',
    history: [
      { id: 2, order_id: 2, status: 'pending', comment: 'Заказ создан, ищем ветеринара', created_at: subHours(3) },
      { id: 3, order_id: 2, status: 'confirmed', comment: 'Ветеринар принял заказ', created_at: subHours(2) },
    ],
  },
  {
    id: 3,
    client_id: 12,
    vet_id: 1,
    pet_id: 7,
    service_id: 5,
    address: 'Москва, Ленинский проспект, 90',
    address_lat: 55.7033,
    address_lng: 37.5540,
    scheduled_at: subHours(1),
    status: 'in_progress',
    notes: null,
    total_price: 4500,
    created_at: subHours(5),
    updated_at: subHours(0.5),
    client_name: 'Козлова Марина Сергеевна',
    client_phone: '+79031112233',
    pet_name: 'Пуговка',
    pet_species: 'Кролик',
    pet_breed: 'Карликовый',
    service_name: 'Стерилизация',
    service_icon: '🩻',
    price_from: 4000,
    price_to: 6000,
    vet_name: 'Иванов Алексей Петрович',
    history: [
      { id: 4, order_id: 3, status: 'pending', comment: 'Заказ создан', created_at: subHours(5) },
      { id: 5, order_id: 3, status: 'confirmed', comment: 'Принят', created_at: subHours(4) },
      { id: 6, order_id: 3, status: 'in_progress', comment: 'Начат приём', created_at: subHours(0.5) },
    ],
  },
  {
    id: 4,
    client_id: 13,
    vet_id: 1,
    pet_id: 8,
    service_id: 2,
    address: 'Москва, Пятницкая, 33',
    address_lat: 55.7430,
    address_lng: 37.6310,
    scheduled_at: subHours(24),
    status: 'completed',
    notes: 'Плановая вакцинация',
    total_price: 1800,
    created_at: subHours(30),
    updated_at: subHours(23),
    client_name: 'Новиков Сергей Владимирович',
    client_phone: '+79055559988',
    pet_name: 'Снежок',
    pet_species: 'Собака',
    pet_breed: 'Самоед',
    service_name: 'Вакцинация',
    service_icon: '💉',
    price_from: 1500,
    price_to: 2500,
    vet_name: 'Иванов Алексей Петрович',
    history: [
      { id: 7, order_id: 4, status: 'pending', comment: 'Заказ создан', created_at: subHours(30) },
      { id: 8, order_id: 4, status: 'confirmed', comment: 'Принят', created_at: subHours(29) },
      { id: 9, order_id: 4, status: 'in_progress', comment: 'Начат приём', created_at: subHours(25) },
      { id: 10, order_id: 4, status: 'completed', comment: 'Завершён успешно', created_at: subHours(23) },
    ],
  },
  {
    id: 5,
    client_id: 14,
    vet_id: 1,
    pet_id: 9,
    service_id: 4,
    address: 'Москва, Патриаршие пруды, 6',
    address_lat: 55.7647,
    address_lng: 37.5936,
    scheduled_at: subHours(48),
    status: 'completed',
    notes: 'Удаление зуба',
    total_price: 5800,
    created_at: subHours(52),
    updated_at: subHours(47),
    client_name: 'Белова Екатерина Ивановна',
    client_phone: '+79164448877',
    pet_name: 'Герцог',
    pet_species: 'Кошка',
    pet_breed: 'Британская',
    service_name: 'Стоматология',
    service_icon: '🦷',
    price_from: 5000,
    price_to: 8000,
    vet_name: 'Иванов Алексей Петрович',
    history: [
      { id: 11, order_id: 5, status: 'pending', comment: 'Заказ создан', created_at: subHours(52) },
      { id: 12, order_id: 5, status: 'confirmed', comment: 'Принят', created_at: subHours(51) },
      { id: 13, order_id: 5, status: 'in_progress', comment: 'Начат приём', created_at: subHours(49) },
      { id: 14, order_id: 5, status: 'completed', comment: 'Завершён успешно', created_at: subHours(47) },
    ],
  },
]
